# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08d0b6c1f6569cff5f2b366d5160d584bad6814f2f03a080a475ffdb8e51b95fab16d783c85732beebbcc14c3c01c81fbfb7ad58faa78c623d8850b5d7cff63a

test:
  secret_key_base: 9db8db79a4b9f70f7637148c83a774703033077a67c3718709d87f8f46c95a435664dd36c727bd4f3023040c969701d984ab8fd049c679010d9c9ffd8feac45f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
